config/routes.rb
War::Application.routes.draw do
  devise_for :user, :controllers => {:registrations => "users/registrations"} do
    get "/users/update_default_settings" => 'users/registrations#update_default_settings' 
  end
  root :to =>"games#index"
  resources :games

  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:players, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :players
    = f.number_field :players
  .field
    = f.label :score
    = f.number_field :score
  .actions
    = f.submit 'Save'

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1#war WAR

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice

%p
  %b Players:
  = @game.players
%p
  %b Score:
  = @game.score

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>War</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>